databases:
  - name: moneywise
    databaseName: moneywise
    user: moneywise_user

services:
  - type: web
    name: moneywise
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moneywise
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false